### ISSUE TITLE
Put all subprojects' generated static pages here

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo.github.io#10]
Aside from the generic info that I've made issues for (and the info I haven't made issues for yet), we should also put all of the HTML files generated by Sphinx here.

There are a few reasons to put it here rather than in each project's `gh-pages` branch.
1. It's easy to write a script that clones a repo, checks out a branch, runs sphinx (or typedoc or whatever) and copies the output to a certain location in this repo. Doing it by checking out an orphan branch and pruning away the non-documentation stuff etc etc is not as easy to script.
2. The generated docs can get pretty big (2.5 MB zipped up for Nengo) so keeping them in a branch in each repo will negatively impact how long it takes to clone each project's repo. By keeping it all in this repo, it means that this one will be a pain to clone, but better for one repo (that many people won't ever clone) to be huge than to have all our repos be large.

Each subproject will be put in a subfolder off the root, and then within that subfolder, there will be a folder for each release. For example, for Nengo there'll be separate copies of the docs at
- https://nengo.ai/nengo/2.0.0
- https://nengo.ai/nengo/2.0.1

and so on. Similarly, there will be a https://nengo.ai/nengo_gui/0.2.0, etc.

The action items needed to get this working (once we have this repo set up in general) are to:
- [ ] Add scripts to check out and build docs for each project.
- [ ] Figure out how to link to those docs from the generic documentation in this repo.

**Comment by Seanny123** [comment]
Do you want the script to:
1. Check out the master branch 
2. Check out the branch specified by a config file
3. Check out the branch specified by a command line arguments

**Comment by Seanny123** [comment]
When you say:
> Figure out how to link to those docs from the generic documentation in this repo.

Do you mean editing the documentation links in each project to link to the most recent documentation posted on GitHub pages?

**Comment by tbekolay** [comment]
> Do you want the script to ...

I don't really envision it being a super general thing; likely there will need to be a slightly different set of actions for different repositories, though there could be a default set of actions for typical Python projects. Nengo GUI, for example, might need additional steps to build the frontend docs.

> Do you mean editing the documentation links in each project to link to the most recent documentation posted on GitHub pages?

Yep. I'm not sure about most recent, but at least point to a valid page on GitHub pages (if we need to update the version we're pointing to, that's fine). This should be possible by setting up [intersphinx mappings](http://www.sphinx-doc.org/en/stable/ext/intersphinx.html) like we do to point to Python and NumPy docs.

**Comment by drasmuss** [comment]
After discussion with Trevor, the conclusion was that this would provide relatively minor benefit in the current doc setup, and makes the documentation build process more complicated, so probably better to just leave things as-is.
