### ISSUE TITLE
Link to model archive

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo.github.io#11]
Have we decided what we're going to do for the model archive? I think we talked about this once and discussed how moving away from Drupal was a priority, but we weren't sure if it could be moved to github pages or not.

**Comment by tbekolay** [comment]
My hope was that models / papers that provide models would be made available as self-contained repos (hosted on Github, bitbucket, whatever) which we can link to on nengo.github.io. First step for that would be to migrate the models currently in http://models.nengo.ca/ elsewhere, likely https://github.com/ctn-archive/. Then we can start curating a list of repositories that contain Nengo models.

That's assuming that we're okay dropping http://models.nengo.ca/ as a generic repository for computational neuroscience models; I don't think we ever had a model outside of the CTN (and not using Nengo) submitted there, so seems like a reasonable thing to do.

**Comment by jgosmann** [comment]
People could submit additions to the list via pull requests or issues.

**Comment by Seanny123** [comment]
May I propose making that list filterable via JavaScript?

**Comment by drasmuss** [comment]
After some internal discussion, our general thoughts are that while an active model repository would be great, an inactive one just ends up being confusing (e.g., the current content of the models repo, as preserved in https://github.com/nengo/nengo.github.io/pull/81, is almost entirely Nengo 1.4 models). We're hoping that more distributed methods of aggregating models will be kept more up to date, and therefore more useful to users even if the list is less "official" than a Nengo-hosted resource. So instead we'd encourage users to post their models on the forums at https://forum.nengo.ai/, or there is also the [nengo topic on github](https://github.com/topics/nengo), which anyone is free to use to tag their projects and make them easily searchable.  If those methods start to seem like they are not keeping up with demand, then we could revisit having an official model repository.
