### ISSUE TITLE
Document version numbering

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo.github.io#2]
- [x] Reference [semantic versioning](http://semver.org/).
- [ ] For backends, versions aren't tied to the frontend version number (summarize https://github.com/nengo/nengo/issues/715)

**Comment by drasmuss** [comment]
Might be useful to have a nengo ecosystem version compatibility chart showing compatibility between different nengo project versions.

**Comment by drasmuss** [comment]
Our plan going forward is to document the supported versions of major dependencies in the changelog of each package (it will be easier to maintain a distributed system like that rather than keeping some centralized information up-to-date).
