### ISSUE TITLE
nengo.ai should have a link to the forum

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo.github.io#28]
So far nengo.ai would redirect to the forum, but it now leads to a new main page that has no obvious link to the forum. That may confuse people who used nengo.ai (instead of forum.nengo.ai) so far to get to the forum.

**Comment by tbekolay** [comment]
a1da92ee7f4c8438095f4e4ff59 (in #27) does this; will try to clean that up this week, or I'll break it into a separate PR.

**Comment by tbekolay** [comment]
Fixed in #27.
