### ISSUE TITLE
Document Python style

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo.github.io#3]
- [x] Generally, we conform to `pep8` and check this through `flake8`
- [x] We use `numpydoc` conventions for docstrings
  - [x] Parameters are ordered as in the call; attributes are alphabetically ordered (see https://github.com/nengo/nengo/pull/959)
- [x] Class members are ordered in a specific order (see https://github.com/nengo/nengo/pull/959)

**Comment by Seanny123** [comment]
Seems to be resolved in the most recent version of the website.
