### ISSUE TITLE
Inline MathJax isn't rendering

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo.github.io#31]
See: https://www.nengo.ai/nengo/examples/learn_associations.html

Tested on both Chrome and Firefox.

**Comment by tbekolay** [comment]
It's currently working for me, though I have had it not work at times. It's due to the MathJax CDN, I think. Do you see a box in the lower left corner that says something about the MathJax loading progess? Can you press F12 and see if the console is spitting out any messages?

**Comment by drasmuss** [comment]
Perhaps related to this https://www.mathjax.org/cdn-shutting-down/?

**Comment by Seanny123** [comment]
@drasmuss that is precisely the cause of the error according to the developer console

**Comment by Seanny123** [comment]
Apparently, the MathJax CDN problem got [fixed in Sphinx 1.5.5](https://github.com/sphinx-doc/sphinx/blob/cdc5b8d575817a4eab4b26fe7bfa400c24341084/CHANGES#L415). So, if the newest build of the website isn't working, despite Sphinx being updated, we might need to open an issue somewhere.

**Comment by tbekolay** [comment]
nengo.github.io was recently rebuilt; if you look at the [current index.html source](https://github.com/nengo/nengo.github.io/blob/master/index.html), we are indeed using cloudflare and not the MathJax CDN, so this should be fixed whenever each individual documentation page is rebuilt.
