### ISSUE TITLE
Add more obvious link to Nengo core documentation

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo.github.io#44]
Finding the Nengo core documentation (which is arguably more important than the documentation of the other subproject) could be easier. The fastest way at the moment seems to be to click on *Nengo projects*, scroll down and click that small *Documetation* button under Nengo core.

It also happened to me repeatedly that I clicked *User Guide* when I was actually looking for the Nengo core user guide (which is different).

**Comment by tbekolay** [comment]
I tend to use the browser's URL bar auto-fill to get to https://www.nengo.ai/nengo/ quickly, but that's definitely not how most people would get there. Any suggestions of where to put it? Maybe a "Core documentation" link in the left sidebar, under Nengo projects?

**Comment by jgosmann** [comment]
Sure, that should be fine.

**Comment by astoeckel** [comment]
I've been struggeling with this as well for a few months now, but never got around to open an issue.

I usually search for a link to the documentation of a software project in a header menu (which arguably doesn't exist on nengo.ai). The problem with the current website is that I always expect the frontend API documentation to be under "Developer Guide" ‒ Nengo users (me included) *are* developers, so this item is named very confusingly. Should be named "Contributor Guide" instead. And when I click "User guide", there is only some longish introduction and I have to scroll around to find the API documentation button, and then click again somewhere else to find the documentation of the Frontend Objects that maybe 95% of all people are interested in.

Plus, the content of the side menu confusingly changes depending on which part of the website I'm on. Once I found the API documentation, "Nengo Modelling API" magically appears under "User Guide". This just makes me really confused. Also the website containing the "Modelling API" is named "frontend_api.html", so I never know what the correct name to type into the URL bar for autocompletion is.

So, to be more in line with other projects  I'd propose having three important buttons at the top, namely

* API Documentation -> https://www.nengo.ai/nengo/frontend_api.html (this is the page I'm always searching for)
* Install -> https://www.nengo.ai/nengo/getting_started.html
* Contribute -> https://www.nengo.ai/nengo/contributing.html

Additionally, the side menu content should be static. I also don't understand why it's called "Table of Contents". I'd expect a Table of Contents to represent the ToC of the current page, and not of the entire website. As a user of the website it's hard to see whether a click will jump to some other part of the page or load another page (which may then entirely replace the ToC, leaving me extremely irritated).

As good examples see

* https://www.rust-lang.org/
* https://golang.org/


Note that I'm aware of where these usability issues come from (nengo.ai being entirely generated by the software-documentation generation tool Sphinx), that doesn't mean that the above usability issues shouldn't be solved long-term. I just try to describe these issues from a naïve user's perspective.

**Comment by tbekolay** [comment]
> Note that I'm aware of where these usability issues come from (nengo.ai being entirely generated by the software-documentation generation tool Sphinx), that doesn't mean that the above usability issues shouldn't be solved long-term. I just try to describe these issues from a naïve user's perspective.

We can move away from using Sphinx to generate these things, but since it can be a lot of work to migrate, it'd have to be proposed and discussed. It would be great to have more web devs on board, especially those with design experience.

**Comment by celiasmith** [comment]
Hopefully this PR addresses @jgosmann suggestions about reorganization and most of those from @astoeckel. Not all of the latter were easy/possible (or occasionally necessary, I felt), but it should be easier to find the API docs.  As well the 'contributor' vs 'developer' difference should no longer be confusing. Moving between core documentation and the main nengo site is also easier. The API is now called 'core api' everywhere (e.g. core_api.html).

**Comment by jgosmann** [comment]
Not sure if all of @astoeckel comments have been addressed, but I'm satisfied.
