### ISSUE TITLE
Add link to Nengo Extras from project listing

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo.github.io#50]
Making a note for myself to make a PR later.

**Comment by drasmuss** [comment]
It's there, under "Core frameworks", assuming this is the page you're talking about https://www.nengo.ai/projects.html?

**Comment by tbekolay** [comment]
He means to add a link to https://www.nengo.ai/nengo-extras/ which I didn't do when I did the nengo-extras release (I think I probably didn't add the pypi link either)
