### ISSUE TITLE
Document for backend developers

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo.github.io#7]
Ported from https://github.com/nengo/nengo/pull/711; the document should take developers through all of the requirements and helper functions for developing a backend.

It should include an explanation of how to run Nengo unit tests, including how the `Simulator.unsupported` attribute works (which was the subject of https://github.com/nengo/nengo/pull/711).

We should also link to existing backends, and provide a process for new backends to be included on the list.

**Comment by drasmuss** [comment]
We've moved away from hosting this kind of content on `nengo.ai`, this would be more of an internal documentation issue.
