### ISSUE TITLE
Neural simulator page - Dispelling common criticisms of Nengo

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo.github.io#72]
### Example 1: PyRates

*Paper*: https://www.biorxiv.org/content/biorxiv/early/2019/04/13/608067.full.pdf

*Quote*:
> However, most often it is not possible to add new models or modeling mechanisms to this pool without considerable effort. This holds true especially, if one still wants to benefit from the parallelization and optimization features of the respective software... Unfortunately, the tools that provide such code generation mechanisms are limited with regards to the model parts they allow to be customized in such a way and the families of neural models they can express.

*Rebuttal*:
https://www.nengo.ai/nengo/examples/usage/rectified_linear.html

### Example 2: DracuLab

*Paper*: https://www.frontiersin.org/articles/10.3389/fninf.2019.00018/full

*Quote*:
> There are excellent simulators for firing rate networks (Aisa et al., 2008; Cofer et al., 2010; Rougier and Fix, 2012; Bekolay et al., 2014; Vitay et al., 2015; Tosi and Yoshimi, 2016), but it is unusual to find rate simulators that take into account connection delays. 

*Rebuttal*:
https://arvoelke.github.io/nengolib-docs/nengolib.synapses.DiscreteDelay.html#nengolib.synapses.DiscreteDelay

### Example 3: TODO ...

**Comment by drasmuss** [comment]
Our thinking is that we should try to modify the documentation more generally to clear up any common misunderstandings like this, rather than having an explicit rebuttals page (it's a bit too easy for the latter to come across as petty/defensive, or it just draws attention to poorly researched papers).

**Comment by arvoelke** [comment]
I agree it shouldn't be an explicit rebuttals page. Will this issue be opened or linked somewhere else?

**Comment by tbekolay** [comment]
No, I think we would take it case-by-case to see if anything should change based on the paper's criticism. Most authors are searching for at least one deficiency that they can point at to show that their tool / network is better for some reason or another. Unbiased review papers would be a different story. The two snippets in the original post I don't think warrant any changes on our part; can you think of any docs changes that make sense as a response to those two?

**Comment by arvoelke** [comment]
Yep, I can. I could make a PR?

**Comment by tbekolay** [comment]
Sounds good!
