### ISSUE TITLE
Landing Page Formatting

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo.github.io#75]
The landing page for nengo.ai (index.rst) looks strange to me (Ubuntu 16.04, Google Chrome 74.0.3729.131) , not sure if it's intentional:

- Large font for all text, including bullets
- Double spaced bullet list
- Because of the large font and bullet spacing, the text doesn't align well with the images on the right.

![screenshot79](https://user-images.githubusercontent.com/18405463/57638126-1a0d0980-757b-11e9-88e6-775cc1a46949.png)

**Comment by tbekolay** [comment]
This seems to be an issue with Sphinx>=2.0.0, as this doesn't happen with earlier versions of Sphinx.

**Comment by drasmuss** [comment]
I believe this is all resolved in the new version of the site.
