### ISSUE TITLE
Learning center / best practices

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo.github.io#9]
The more general parts of the CTN best practices guides could live in this repo.
- On GDrive: https://drive.google.com/drive/folders/0B8Q9l8-ja4yTNDY3eF9MZmJBMHM
- https://github.com/ctn-waterloo/best-practices

**Comment by celiasmith** [comment]
Sure tging

**Comment by celiasmith** [comment]
are you suggesting to move the stuff from the gdrive to the repo?

Trevor Bekolay wrote:

**Comment by tbekolay** [comment]
> are you suggesting to move the stuff from the gdrive to the repo?

Possibly, if it's generic enough

**Comment by celiasmith** [comment]
makes sense to me :)

Trevor Bekolay wrote:

**Comment by drasmuss** [comment]
We've moved away from hosting this kind of content on `nengo.ai`, so it's probably better to leave it where it is or move it to some other location (e.g. internal documentation or CNRG website) as appropriate.
