### ISSUE TITLE
Local anchors ignore header

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo.github.io#92]
When you go to any page with an anchor (e.g., https://www.nengo.ai/nengo/frontend-api.html#nengo.Ensemble), the related text is anchored to the top of the page, assuming the top navigation header is not there. But, with the top header there, part of the anchored text is occluded:

![image](https://user-images.githubusercontent.com/1971583/70768835-fdb19500-1d34-11ea-859f-453b4bb77f22.png)

**Comment by arvoelke** [comment]
Also posted on another repo: https://github.com/nengo/nengo-sphinx-theme/issues/50 -- Good to see it reproduced and noticed though by someone else.

**Comment by drasmuss** [comment]
Going to close this in favour of https://github.com/nengo/nengo-sphinx-theme/issues/50, but I'll add the note there that this is related to the navbar.
